### ISSUE TITLE
Athlete data of some athletes lead to strange behavior

### ISSUE THREAD

**Issue by dorianim** [ralfbecker/ranking#3]
Hi @ralfbecker ,

when trying to get the athlete data of some athletes, a strange error occurs:
First, it throws an HTTP 500 error with this error message:
```
ranking/src/Export.php (2171)
<h3>Ein Fehler ist aufgetreten.</h3>
<pre><b>Unsupported operand types: int - string (0)</b>

</pre>
```
Then, it starts to render egroupware.

Affected links:
- Oleksiy Yurko https://www.digitalrock.de/egroupware/ranking/json.php?person=7618
- Yaroslav Topal https://www.digitalrock.de/egroupware/ranking/json.php?person=7619

The referenced line of code:
https://github.com/ralfbecker/ranking/blob/638b9e82a67c8b6f4fb3ea3d0200be330c30fca6/src/Export.php#LL2171C1-L2171C4

Would be nice to get this fixed :)

**Comment by ralfbecker** [comment]
Thx for reporting this, it's fixed now: https://github.com/ralfbecker/ranking/commit/c06d98002a034fc4ecc29c5552f4ad468692f37b

You won't see much with this request, as the error was caused due the athlete choose not to show his profile anymore (and the updated PHP version).

Ralf

**Comment by dorianim** [comment]
Thanks!
